### ISSUE TITLE
MaterialUI implementation not working

### ISSUE THREAD

**Issue by parksj10** [react-theming/storybook-addon#11]
Not sure if the docs are out of date, but I'm trying to implement this plugin for MaterialUI

## Using with Material-UI

```js
// theme.js
import { red } from '@material-ui/core/colors';

// A custom theme for this app
const theme = {
  palette: {
    primary: {
      main: '#556cd6',
    },
    secondary: {
      main: '#19857b',
    },
    error: {
      main: red.A400,
    },
    background: {
      default: '#fff',
    },
  },
};

export default theme;
```

```js
// .storybook/preview.js

import { ThemeProvider } from '@material-ui/core';
import { createMuiTheme } from '@material-ui/core/styles';
import { addDecorator } from '@storybook/react';
import { withThemes } from '@react-theming/storybook-addon';

import theme from '../src/theme';

const providerFn = ({ theme, children }) => {
  const muTheme = createMuiTheme(theme);
  return <ThemeProvider theme={muTheme}>{children}</ThemeProvider>;
};

// pass ThemeProvider and array of your themes to decorator
addDecorator(withThemes(null, [theme]));
```

```js
// index.js

import React from 'react';
import ReactDOM from 'react-dom';
import { ThemeProvider } from '@material-ui/core/styles';
import { createMuiTheme } from '@material-ui/core/styles';
import App from './App';
import theme from './theme';

ReactDOM.render(
  <ThemeProvider theme={createMuiTheme(theme)}>
    <App />
  </ThemeProvider>,
  document.querySelector('#root'),
);

```

Although the above example doesn't even seem to reference `providerFn`, I tried to use the following

```js
// preview.js

import { withThemes } from '@react-theming/storybook-addon';
import { withThemeProvider } from './decorators';
import { theme } from '../src/styles/theme';

addDecorator(withThemes(null, [theme], { withThemeProvider }));
```

```js
// decorators.js

import { MuiThemeProvider} from '@material-ui/core';
import { theme } from '../src/styles/theme';

export const withThemeProvider = ({ children }) => {
  return <MuiThemeProvider theme={theme}>{children}</MuiThemeProvider>;
}
```

and I get the following error in storybook
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: null.
    at createFiberFromTypeAndProps (http://localhost:4400/vendors~main.552165771ec047452ec4.bundle.js:204846:21)
    at createFiberFromElement (http://localhost:4400/vendors~main.552165771ec047452ec4.bundle.js:204874:15)
    at reconcileSingleElement (http://localhost:4400/vendors~main.552165771ec047452ec4.bundle.js:193845:23)
    at reconcileChildFibers (http://localhost:4400/vendors~main.552165771ec047452ec4.bundle.js:193905:35)
    at reconcileChildren (http://localhost:4400/vendors~main.552165771ec047452ec4.bundle.js:196783:28)
    at mountIndeterminateComponent (http://localhost:4400/vendors~main.552165771ec047452ec4.bundle.js:197683:5)
    at beginWork (http://localhost:4400/vendors~main.552165771ec047452ec4.bundle.js:198842:16)
    at HTMLUnknownElement.callCallback (http://localhost:4400/vendors~main.552165771ec047452ec4.bundle.js:183738:14)
    at Object.invokeGuardedCallbackDev (http://localhost:4400/vendors~main.552165771ec047452ec4.bundle.js:183787:16)
    at invokeGuardedCallback (http://localhost:4400/vendors~main.552165771ec047452ec4.bundle.js:183849:31)
```

**Comment by parksj10** [comment]
Dug into your package... and it seems you've statically named/referenced `providerFn`... Got above working by changing

```js
 addDecorator(withThemes(null, [theme], { withThemeProvider }));
```

to

```js
addDecorator(withThemes(null, [theme], { providerFn: withThemeProvider }));
```

**Comment by UsulPro** [comment]
Thanks @parksj10 
Indeed you need to pass providerFn as it shown in documentation https://github.com/react-theming/storybook-addon#usage

Did you solve your issue?

**Comment by parksj10** [comment]
Yes, sovled it. just as a note, the MaterialUI portion of the documentation seems incorrect

namely:
```
// pass ThemeProvider and array of your themes to decorator
addDecorator(withThemes(null, [theme]));
```

should be

```
// pass ThemeProvider and array of your themes to decorator
addDecorator(withThemes(null, [theme], { providerFn }));
```
