### ISSUE TITLE
Transitions are not working using MUI 5 on Storybook (6.4.17)

### ISSUE THREAD

**Issue by mastepanoski** [react-theming/storybook-addon#48]
I am trying to test a component, an AppBar with a User Menu Menu. I suspect that the issue is related to theming MUI5 that is using Emotion 11. The issue does not happen running on NextJS (production and development). 

The error is triggered only on Storybook when I want to press a MenuItem (dropdown with transition) the following exception is triggered:
  
```

  missing } after function body

  result@http://localhost:6006/vendors-node_modules_mui_icons-material_AccountCircle_js-node_modules_mui_icons-material_Busi-48779a.iframe.bundle.js:116272:17
  ./node_modules/@mui/material/Grow/Grow.js/Grow/handleEnter<@http://localhost:6006/vendors-node_modules_mui_icons-material_AccountCircle_js-node_modules_mui_icons-material_Busi-48779a.iframe.bundle.js:9225:36
  ./node_modules/@mui/material/Grow/Grow.js/Grow/normalizedTransitionCallback/<@http://localhost:6006/vendors-node_modules_mui_icons-material_AccountCircle_js-node_modules_mui_icons-material_Busi-48779a.iframe.bundle.js:9202:17
```

But if I change main.js setting features: { emotionAlias: false }, it triggers:

```
  transform is not defined
  
  @http://localhost:6006/vendors-node_modules_mui_icons-material_AccountCircle_js-node_modules_mui_icons-material_Busi-48779a.iframe.bundle.js line 116912 > eval:1:264
  @http://localhost:6006/vendors-node_modules_mui_icons-material_AccountCircle_js-node_modules_mui_icons-material_Busi-48779a.iframe.bundle.js line 116912 > eval:1:232
  result@http://localhost:6006/vendors-node_modules_mui_icons-material_AccountCircle_js-node_modules_mui_icons-material_Busi-48779a.iframe.bundle.js:116913:18
  closedMixin@http://localhost:6006/main.iframe.bundle.js:705:28
  ./src/features/commons/components/AppBar.js/Drawer<@http://localhost:6006/main.iframe.bundle.js:756:34
```

My preview.js file:

```
      import { ThemeProvider, StyledEngineProvider } from '@mui/material/styles'
      import CssBaseline from '@mui/material/CssBaseline'
      import { withThemes } from '@react-theming/storybook-addon'
      import { RouterContext } from 'next/dist/shared/lib/router-context' // next 11.1
      import { ToastProvider } from 'react-toast-notifications'
      import * as nextImage from 'next/image'
      import 'dayjs'
      import 'dayjs/locale/en'
      import 'dayjs/locale/es'
      
      import {
        LocaleProviderMock
      } from '../src/features/commons/__mocks__/hooks/useTranslationMock'
      
      import commonEs from '../public/locales/es/common.json'
      import loginEs from '../public/locales/es/login.json'
      import dashboardEs from '../public/locales/es/dashboard.json'
      import contractEs from '../public/locales/es/contract.json'
      import eventEs from '../public/locales/es/event.json'
      import languageSwitcherEs from '../public/locales/es/languageSwitcher.json'
      import usersEs from '../public/locales/es/users.json'
      import organizationsEs from '../public/locales/es/organizations.json'
      
      import theme from '../src/theme'
      import '../styles/globals.css'
      import 'nprogress/nprogress.css'
      
      const locale = Object.freeze({
        common: commonEs,
        login: loginEs,
        dashboard: dashboardEs,
        contract: contractEs,
        event: eventEs,
        languageSwitcher: languageSwitcherEs,
        users: usersEs,
        organizations: organizationsEs
      })
      
      const CThemeProvider = ({ children, theme }) => (
        <StyledEngineProvider injectFirst>
          <ThemeProvider theme={theme}>
            <ToastProvider autoDismissTimeout={7000} autoDismiss placement='bottom-right'>
              <LocaleProviderMock locale={locale}>
                <CssBaseline />
                {children}
              </LocaleProviderMock>
            </ToastProvider>
          </ThemeProvider>
        </StyledEngineProvider>
      )
      
      Object.defineProperty(nextImage, 'default', {
        configurable: true,
        value: props => {
          return (
            <div
              style={{
                position: 'relative'
              }}
            >
              <img
                style={{
                  objectFit: 'cover',
                  minWidth: '100%',
                  minHeight: '100%',
                  maxWidth: '100%',
                  maxHeight: '100%'
                }}
                {...props}
              />
            </div>
          )
        },
      })
      
      export const decorators = [
        withThemes(CThemeProvider, [theme])
      ]
      
      export const parameters = {
        nextRouter: {
          Provider: RouterContext.Provider,
          path: '/', // defaults to `/`
          asPath: '/', // defaults to `/`
          query: {}, // defaults to `{}`
          push() {
          } // defaults to using addon actions integration,
          //   can override any method in the router
        }
      }
```

My main.js file:

```
  const path = require('path')
  
  module.exports = {
    stories: ['../src/features/**/__stories__/**/*.stories.js'],
    addons: [
      '@react-theming/storybook-addon',
      'storybook-addon-next-router'
    ],
    features: {
      emotionAlias: false,
      postcss: false
    },
    core: {
      builder: 'webpack5'
    },
    webpackFinal: async (baseConfig) => {
      // Modify or replace config. Mutating the original reference object can cause unexpected bugs.
      const { module = {} } = baseConfig
  
      const newConfig = {
        ...baseConfig,
        module: {
          ...module,
          rules: [...(module.rules || [])]
        }
      }
  
      //
      // CSS Modules
      // Many thanks to https://github.com/storybookjs/storybook/issues/6055#issuecomment-521046352
      //
  
      // First we prevent webpack from using Storybook CSS rules to process CSS modules
      newConfig.module.rules.find(
        rule => rule.test.toString() === '/\\.css$/'
      ).exclude = /\.module\.css$/
  
      // Then we tell webpack what to do with CSS modules
      newConfig.module.rules.push({
        test: /\.module\.css$/,
        include: path.resolve(__dirname, '../features'),
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1,
              modules: true
            }
          }
        ]
      })
  
      return newConfig
    }
  }
```

My AppBar.js:

```
  import React, { useState } from 'react'
  import { styled, useTheme } from '@mui/material/styles'
  import MuiDrawer from '@mui/material/Drawer'
  import MuiAppBar from '@mui/material/AppBar'
  import Toolbar from '@mui/material/Toolbar'
  import List from '@mui/material/List'
  import withStyles from '@mui/styles/withStyles'
  import Typography from '@mui/material/Typography'
  import Divider from '@mui/material/Divider'
  import IconButton from '@mui/material/IconButton'
  import MenuIcon from '@mui/icons-material/Menu'
  import ChevronLeftIcon from '@mui/icons-material/ChevronLeft'
  import ChevronRightIcon from '@mui/icons-material/ChevronRight'
  import ListItem from '@mui/material/ListItem'
  import ListItemIcon from '@mui/material/ListItemIcon'
  import ListItemText from '@mui/material/ListItemText'
  import Avatar from '@mui/material/Avatar'
  import AccountCircle from '@mui/icons-material/AccountCircle'
  import MenuItem from '@mui/material/MenuItem'
  import ExitToAppIcon from '@mui/icons-material/ExitToApp'
  import Menu from '@mui/material/Menu'
  import Link from 'next/link'
  import PeopleIcon from '@mui/icons-material/People'
  import CircularProgress from '@mui/material/CircularProgress'
  
  const drawerWidth = 240
  
  const openedMixin = (theme) => ({
    width: drawerWidth,
    transition: theme.transitions.create('width', {
      easing: theme.transitions.easing.sharp,
      duration: theme.transitions.duration.enteringScreen
    }),
    overflowX: 'hidden'
  })
  
  const closedMixin = (theme) => ({
    transition: theme.transitions.create('width', {
      easing: theme.transitions.easing.sharp,
      duration: theme.transitions.duration.leavingScreen
    }),
    overflowX: 'hidden',
    width: `calc(${theme.spacing(7)} + 1px)`,
    [theme.breakpoints.up('sm')]: {
      width: `calc(${theme.spacing(9)} + 1px)`
    }
  })
  
  const DrawerHeader = styled('div')(({ theme }) => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    padding: theme.spacing(0, 1),
    // necessary for content to be below app bar
    ...theme.mixins.toolbar
  }))
  
  const AppBar = styled(MuiAppBar, {
    shouldForwardProp: (prop) => prop !== 'open'
  })(({ theme, open }) => ({
    zIndex: theme.zIndex.drawer + 1,
    transition: theme.transitions.create(['width', 'margin'], {
      easing: theme.transitions.easing.sharp,
      duration: theme.transitions.duration.leavingScreen
    }),
    ...(open && {
      marginLeft: drawerWidth,
      width: `calc(100% - ${drawerWidth}px)`,
      transition: theme.transitions.create(['width', 'margin'], {
        easing: theme.transitions.easing.sharp,
        duration: theme.transitions.duration.enteringScreen
      })
    })
  }))
  
  const Drawer = styled(MuiDrawer, { shouldForwardProp: (prop) => prop !== 'open' })(
    ({ theme, open }) => ({
      width: drawerWidth,
      flexShrink: 0,
      whiteSpace: 'nowrap',
      boxSizing: 'border-box',
      ...(open && {
        ...openedMixin(theme),
        '& .MuiDrawer-paper': openedMixin(theme)
      }),
      ...(!open && {
        ...closedMixin(theme),
        '& .MuiDrawer-paper': closedMixin(theme)
      })
    })
  )
  
  const StyledMenu = withStyles({
    paper: {
      border: '1px solid #d3d4d5'
    }
  })((props) => (
    <Menu
      elevation={0}
      // getContentAnchorEl={null}
      anchorOrigin={{
        vertical: 'bottom',
        horizontal: 'center'
      }}
      transformOrigin={{
        vertical: 'top',
        horizontal: 'center'
      }}
      {...props}
    />
  ))
  
  export default function MiniDrawer ({
    translator: t,
    signOutState = null,
    onSignOut: handleSignOut
  }) {
    const theme = useTheme()
    const [open, setOpen] = useState(false)
    const [anchorEl, setAnchorEl] = useState(null)
  
    const handleMenu = (event) => {
      setAnchorEl(event.currentTarget)
    }
  
    const handleClose = () => {
      setAnchorEl(null)
    }
  
    const handleDrawerOpen = () => {
      setOpen(true)
    }
  
    const handleDrawerClose = () => {
      setOpen(false)
    }
  
    return (
      <>
        <AppBar position='fixed' open={open}>
          <Toolbar>
            <IconButton
              color='inherit'
              aria-label='open drawer'
              onClick={handleDrawerOpen}
              edge='start'
              sx={{
                marginRight: '36px',
                ...(open && { display: 'none' })
              }}
            >
              <MenuIcon />
            </IconButton>
            <Link href='/' passHref>
              <Typography style={{ cursor: 'pointer' }} variant='h6' noWrap component='div'>
                MyApp
              </Typography>
            </Link>
            <Typography sx={{ flexGrow: 1 }} />
            <div>
              <IconButton
                aria-label='account of current user'
                aria-controls='menu-appbar'
                aria-haspopup='true'
                onClick={handleMenu}
                color='inherit'
                size='large'
              >
                <AccountCircle />
              </IconButton>
              <StyledMenu
                id='customized-menu'
                anchorEl={anchorEl}
                keepMounted
                open={Boolean(anchorEl)}
                onClose={handleClose}
              >
                {
                  !signOutState?.processing
                    ? (
                      <MenuItem onClick={handleSignOut}>
                        <ListItemIcon>
                          <ExitToAppIcon fontSize='small' />
                        </ListItemIcon>
                        <ListItemText primary={t('dashboard:sign_out')} />
                      </MenuItem>
                      )
                    : (
                      <MenuItem>
                        <CircularProgress color='inherit' size={24} />
                      </MenuItem>
                      )
                }
              </StyledMenu>
            </div>
          </Toolbar>
        </AppBar>
        <Drawer variant='permanent' open={open}>
          <DrawerHeader>
            <Avatar alt='MyApp' src='/favicon.ico' />
            <IconButton onClick={handleDrawerClose} size='large'>
              {theme.direction === 'rtl' ? <ChevronRightIcon /> : <ChevronLeftIcon />}
            </IconButton>
          </DrawerHeader>
          <Divider />
          <List>
             <Link href='/users' passHref>
              <ListItem button key={t('dashboard:users')}>
                <ListItemIcon>
                  {' '}
                  <PeopleIcon />{' '}
                </ListItemIcon>
                <ListItemText primary={t('dashboard:users')} />
              </ListItem>
            </Link>
          </List>
        </Drawer>
      </>
    )
  }
```
  
And AppBar.stories.js

```
  /* global module */
  
  import React from 'react'
  import { storiesOf } from '@storybook/react'
  
  import AppBar from '../AppBar'
  import useSignOutMock from '../../__mocks__/hooks/useSignOutMock'
  import useTranslationMock from '../../__mocks__/hooks/useTranslationMock'
  
  function AppBarStory () {
    const {
      signOutState,
      signOut: handleSignOut
    } = useSignOutMock()
    const { translator } = useTranslationMock()
  
    return (
      <AppBar
        translator={translator}
        signOutState={signOutState}
        onSignOut={handleSignOut}
      />
    )
  }
  
  storiesOf('Common Components', module)
    .add('AppBar Component', () => (
      <AppBarStory />
    ))
```
I fixed it disabling storybook-addon and doing my own decorator:

```
      import { ThemeProvider, StyledEngineProvider } from '@mui/material/styles'
      import CssBaseline from '@mui/material/CssBaseline'
      import { RouterContext } from 'next/dist/shared/lib/router-context' // next 11.1
      import { ToastProvider } from 'react-toast-notifications'
      import * as nextImage from 'next/image'
      import 'dayjs'
      import 'dayjs/locale/en'
      import 'dayjs/locale/es'
      
      import {
        LocaleProviderMock
      } from '../src/features/commons/__mocks__/hooks/useTranslationMock'
      
      import commonEs from '../public/locales/es/common.json'
      import loginEs from '../public/locales/es/login.json'
      import dashboardEs from '../public/locales/es/dashboard.json'
      import contractEs from '../public/locales/es/contract.json'
      import eventEs from '../public/locales/es/event.json'
      import languageSwitcherEs from '../public/locales/es/languageSwitcher.json'
      import usersEs from '../public/locales/es/users.json'
      import organizationsEs from '../public/locales/es/organizations.json'
      
      import theme from '../src/theme'
      import '../styles/globals.css'
      import 'nprogress/nprogress.css'
      
      const locale = Object.freeze({
        common: commonEs,
        login: loginEs,
        dashboard: dashboardEs,
        contract: contractEs,
        event: eventEs,
        languageSwitcher: languageSwitcherEs,
        users: usersEs,
        organizations: organizationsEs
      })
      
      const CThemeProvider = ({ children, theme }) => (
        <StyledEngineProvider injectFirst>
          <ThemeProvider theme={theme}>
            <ToastProvider autoDismissTimeout={7000} autoDismiss placement='bottom-right'>
              <LocaleProviderMock locale={locale}>
                <CssBaseline />
                {children}
              </LocaleProviderMock>
            </ToastProvider>
          </ThemeProvider>
        </StyledEngineProvider>
      )
      
      Object.defineProperty(nextImage, 'default', {
        configurable: true,
        value: props => {
          return (
            <div
              style={{
                position: 'relative'
              }}
            >
              <img
                style={{
                  objectFit: 'cover',
                  minWidth: '100%',
                  minHeight: '100%',
                  maxWidth: '100%',
                  maxHeight: '100%'
                }}
                {...props}
              />
            </div>
          )
        },
      })
      
      export const decorators = [
        Story => (
          <CThemeProvider theme={theme}>
            <Story />
          </CThemeProvider>
        )
      ]
      
      export const parameters = {
        nextRouter: {
          Provider: RouterContext.Provider,
          path: '/', // defaults to `/`
          asPath: '/', // defaults to `/`
          query: {}, // defaults to `{}`
          push() {
          } // defaults to using addon actions integration,
          //   can override any method in the router
        }
      }
```

**Comment by Ivan-Parushev** [comment]
I can't even get it to work with MUI v5.
I am getting the following error:
`vendors-node_modules_react-theming_storybook-addon_dist_manager_register_js-node_modules_stor-20c72e.manager.bundle.js:3175 Uncaught TypeError: Cannot read properties of undefined (reading 'secondary')`

**Comment by JohnRandom** [comment]
@Ivan-Parushev that one I was actually able to fix: the example in the README.md of this repo is misleading. You need to need to make sure to pass a fully expanded theme into the decorator function:
```
const fullTheme = createTheme(theme);

export const decorators = [
  withThemes(null, [fullTheme], { providerFn }),
];
```

But when you do, the next issue becomes:

```
VM1792:1 Uncaught ReferenceError: values is not defined
    at up (eval at result (index.js:320:1), <anonymous>:1:34)
    at Object.up (index.js:321:1)
    at createMixins (createMixins.js:20:1)
    at createTheme (createTheme.js:34:1)
    at providerFn (preview.js:8:1)
    at CurrentThemeProvider (index.js:49:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateFunctionComponent (react-dom.development.js:17356:1)
    at beginWork (react-dom.development.js:19063:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
```

So, that's where I'm stuck at right now.

**Comment by 123joshuawu** [comment]
@JohnRandom try the solution they put here https://github.com/react-theming/storybook-addon/issues/30#issuecomment-892844261

``` javascript
const providerFn = ({ children, theme }) => {
  const serialTheme = JSON.parse(JSON.stringify(theme));
  const muiTheme = createTheme(serialTheme);

  return (
    <StyledEngineProvider injectFirst>
      <ThemeProvider theme={muiTheme}>
        <CssBaseline />
        {children}
      </ThemeProvider>
    </StyledEngineProvider>
  );
};
```
